export const GET_DAILY_START = "GET_DAILY_START";
export const GET_DAILY_SUCCESS = "GET_DAILY_SUCCESS";
export const GET_DAILY_ERROR = "GET_DAILY_ERROR";
export const GET_WEEKLY_START = "GET_WEEKLY_START";
export const GET_WEEKLY_SUCCESS = "GET_WEEKLY_SUCCESS";
export const GET_WEEKLY_ERROR = "GET_WEEKLY_ERROR";
export const SET_CITIES = "SET_CITIES";

